FROM mcr.microsoft.com/mssql/server:2019-CU12-ubuntu-20.04

ENV ACCEPT_EULA=Y
ENV SA_PASSWORD=SqlServer@123
ENV MSSQL_PID=Express

COPY CEM/ /var/opt/sqlserver/

ENTRYPOINT ["/bin/bash", "/var/opt/sqlserver/SqlCmdStartup.sh"]
